config/routes.rb
Rails.application.routes.draw do
  root 'cvs#index'
  resources :cvs
  get 'about', to: 'cvs#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cv.rb
class Cv < ApplicationRecord
  validates :company, presence: true, length: {maximum: 140, minimum: 3}
  validates :description, presence: true, length: {maximum: 500, minimum: 10}
  validates :dates, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  
  def index

  end

  def new
    @cv = Cv.new
  end

  def create
    @cv = Cv.create (cv_params)
    if @cv.invalid?
      flash[:error] = '<strong> Could not save. </strong> All fields are required.'
    end
    redirect_to root_path
  end

  def about

  end

  private

  def cv_params
    params.require(:cv).permit(:company, :description, :dates)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/digicvs_helper.rb
module DigicvsHelper
end

app/views/cvs/about.html.erb
<div class="col-10 offset-1 about">
  <h1> About digiCV </h1>

  <center>
    <p>

      digiCV was built by <a target= "_blank" href="https://github.com/snsmith92"> Sherzel Smith Williams</a>, a Firehose Project bootcamp student as part of a quiz. <strong> She hopes she passed the test! </strong> 
    </p>

    <p>
      digiCV is for people who have grown tired of repeatedly and monotonously entering their CV details into a remote website.
    </p>
    <br />
    <br />
    <p> 
      To learn more about the vision behind digiCV (or to let Sherzel know if she passed or not), please send us an <a href="mailto:sherzelsmith@gmail.com">email</a>!
  </center>
  
  <br />

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/cvs/index.html.erb
<div class="col-10 offset-1">
  <h1>Welcome to digiCV</h1>
    <center>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Upload your CV Details
    </button>
    </center>
    <br />
    <br />
  <h2> The digital CV platform </h2>

  <br />
  <br />

  <div class="description">
    <p> digiCV allows users to upload their CV details into a digital entry form that can be easily uploaded with the click of a button to online job applications. </p>

    <p> No more tediously typing out the contents of your CV for each and every job application! digiCV knows all your details and fills them all in - <strong>instantly</strong> ! </p>
  </div>
  
  <br />
  
  <hr>
  
  <br />
  
  <h2> How does it work? </h2> 

</div>

<div class="box">
    <h4>1. Create your account</h4>
      <p>
        Create an account using our easy sign up tool
      </p>
</div>

<div class="box2">
    <h4>2. Enter your CV details using the digiCV tool</h4>
      <p>
        Fill out your CV using the digiCV tool which can interpret PDFs and DOCX files
      </p>
</div>

<br class="clear" />

<div class="box">
    <h4>3. Install the digiCV web browser plugin</h4>
      <p>
        Simply install our browser plugin to automatically load your CV info into online job applications
      </p>
</div>

<div class="box2">
    <h4>4. Find the job of your dreams - fast! </h4>
      <p>
        Start using digiCV to apply for jobs!
      </p>
</div>
<br />
<br />
<br />
<br />
<br />
<br />

app/views/cvs/new.html.erb
<h1> Enter your CV details </h1>
<%= simple_form_for @cv do |f| %>
  <%= f.input :company %>
  <%= f.input :description %>
  <%= f.input :dates %>
  <br />
  <%= f.submit 'Upload', class: 'btn btn-danger' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digicv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="row">
        <div class="col-6">
          <%= link_to root_path, class: 'logo-link' do %>
            <div class="logo-style">
              dc
            </div>
          <% end%>
        </div>
        <div class="col-6 offset-1 offset-sm-0 col-sm-5 links">
          <%= link_to 'About Us', about_path %>
          &nbsp;&nbsp;&nbsp;
          <%= link_to 'CV Upload', new_cv_path %>
        </div>
      </header>

  <br class="clear"> 

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Enter your CV Details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= simple_form_for Cv.new do |f| %>
            <div class="modal-body">
              <%= f.input :company, label: "What Company Did You Work For?" %>
              <br />
              <%= f.input :description, label: "What type of work did you do?" %>
              <br />
              <%= f.input :dates, label: "When did you work for the company?" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Upload' , class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <br class = "clear" />

    <div class= "container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </body> 

</html>